FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000:3000

# Define the command to run the application
CMD ["npm", "run", "start:prod"]